config/routes.rb
Rails.application.routes.draw do
  root to:'home#index'
  patch '/capture', to: 'pokemons#capture', as: 'capture'
  patch '/damage', to: 'pokemons#damage', as: 'damage'
  devise_for :trainers
  resources :trainers
  resources :pokemons
  delete '/delete', to:'pokemons#destroy', as: 'destroy'
  post '/pokemons/new', to: 'pokemons#new', as: 'new'
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	
	belongs_to :trainer
	validates :name, presence: true
	validates :name, uniqueness: true

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pokemons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    trainerless_pokemon = Pokemon.where(trainer:nil)
    @pokemon = trainerless_pokemon.sample
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

 	def new
  	end

  	def create

	    @pokemon = Pokemon.new(pokemon_params) 
	    @pokemon.level = 1
	    @pokemon.health = 100
	    @pokemon.trainer = current_trainer
	    
	    if @pokemon.save
	    	redirect_to trainer_path(@current_trainer) 
 		else 
 			flash[:error] = @pokemon.errors.full_messages.to_sentence
 			redirect_to new_pokemon_path
 		end

 	end

 	def capture

		@pokemon = Pokemon.find(params[:id]) 
		@pokemon.trainer = current_trainer 
		@pokemon.save 
		redirect_to root_path

	end	

  	def damage
  		
		@pokemon = Pokemon.find(params[:id]) 
		@pokemon.health -= 10

		if @pokemon.health <= 0
			@pokemon.destroy 
		else 
			@pokemon.save 
		end

		redirect_to trainer_path(@pokemon.trainer_id)

	end

	def destroy

		@pokemon = Pokemon.find(params[:id])
		@pokemon.destroy
		redirect_to trainer_path(@pokemon.trainer_id)

	end

	
 private
  def pokemon_params

    params.require(:pokemon).permit(:name)

  end



end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :authenticate_trainer!

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'PokePortal Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if trainer_signed_in? %>
  <li><%= link_to 'Edit Your Trainer', edit_trainer_registration_path %></li>
  <li><%= link_to 'Log Out', destroy_trainer_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_trainer_session_path %></li>
  <li><%= link_to 'Join PokePortal', new_trainer_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsdecal Proj1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Railsdecal Proj1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pokemons/new.html.erb
<h3> Create a Pokemon </h3>

<%= simple_form_for Pokemon.new, url: {action: "create"} do |f| %>
  Name <%= f.text_field :name %>
  <%= f.submit "Make" %>

<% end %>

app/views/trainers/_trainer.html.erb
<td><%= link_to trainer.name, trainer %></td>
<td><%= link_to trainer.email, trainer %></td>

app/views/trainers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Trainers</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @trainers.each do |trainer| %>
            <tr>
              <%= render trainer %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>

<p>Pokemons:</p>

    <ul>

        <% @trainer.pokemons.each do |pokemon| %>
            <li><%= pokemon.name %>: <%= pokemon.level %>, Health: <%= pokemon.health %> 
                <%= button_to "Damage!", damage_path(id: pokemon), :class => "button medium", :method => :patch %>
            </li>       
        <% end %>
        
        <% if @trainer == current_trainer %>
                <%= button_to "Make New Pokemon", new_pokemon_path %> 
        <% end %>

    </ul>